const EXERCISES = [
    // Chest
      "Bench press", 
      "Incline chest press", 
      "Chest press", 
      "Decline chest press", 
      "Incline dumbell press", 
      "Flat dumbell press", 
      "Laying chest press",
      "Laying incline chest press",
      "Peck deck",
      "Dips",
    // Back
      "Machine rows",
      "Cable rows",
      "Barbell rows",
      "Lat pulldown",
      "Bicep pulldown",
      "Seated pullovers",
      "Cable Pullovers",
      "Pullups",
    // Legs
      "Barbell Squats",
      "Leg press",
      "Deadlifts",
      "Kickbacks",
      "Hip thrusts",
      "Leg extentions",
      "Laying leg curls",
      "Seated leg curls",
    // Delts
      "Front raises",
      "Shoulder press",
      "Barbell overhead press",
      "Standing Lateral raises",
      "Machine Lateral raises",
      "Leaning Lateral raises",
      "Machine Reardelt flyes",
      "Cable Reardelt flyes",
      "Reardelt rows",
    // Arms
      "Skullcrushers",
      "Tricep pushdowns",
      "Katana Tricep extentions",
      "Seated dips",
      "Unilateral Tricep extentions",
      "Dumbell Bicep curl",
      "Barbell Bicep curl",
      "Cable Bicep curl",
      "Dumbell Hammer curl",
      "Cable Hammer curl",
      "Reverse curls",
      "Bayesian curls",
    // Delts
      "Weighted situps",
      "Weighted crunches",
      "Legg raises"

]